vich_uploader:
    db_driver: orm

    mappings:
        image_download:
            uri_prefix: '%app.path.image_download%'
            upload_destination: '%kernel.project_dir%/public/images/download'
